Prevent NaN
yachtcaptain23/publishers pull request #13
Opened 2018-09-19 17:20 UTC by dlipeles

Submitter Checklist:

- [ ] Submitted a [ticket](https://github.com/brave-intl/publishers/issues) for my issue if one did not already exist.
- [ ] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [ ] Tagged reviewers.

Test Plan:

Reviewer Checklist:

Tests
- [ ] Adequate test coverage exists to prevent regressions

Security:
- [ ] No raw SQL -- Always prefer ActiveRecord query helpers ([more info on StackOverflow](https://stackoverflow.com/questions/41410752/rails-5-sql-injection#41452695))
- [ ] XSS is mitigated -- Avoid `html_safe` and `raw`; escape untrusted content from users and 3rd party APIs ([Rails XSS guide](https://brakemanpro.com/2017/09/08/cross-site-scripting-in-rails) and [OWASP XSS Prevention Cheat Sheet](https://www.owasp.org/index.php/XSS_(Cross_Site_Scripting)_Prevention_Cheat_Sheet))

2018-09-19 17:29 UTC, yachtcaptain23 commented on app/javascript/packs/brave_rewards_banner_display.jsx
> +         donationAmounts = [1, 5, 10]
From a UX perspective, this is weird. I think the easier solution is to support strings or not verifying until the user is done typing or verifying upon submit.

2018-09-19 17:29 UTC, yachtcaptain23 requested changes
Comments in-line

2018-09-20 02:46 UTC, yachtcaptain23 commented
I'm seeing this, which shouldn't happen: 

![image](https://user-images.githubusercontent.com/8647607/45792909-a6616980-bc44-11e8-837e-eb5772fa146a.png)

2018-09-20 17:30 UTC, dlipeles commented
I see why that's happening, the way brave-ui implemented the component it was never meant to have two buttons with the same token value. They are using token value as an identifier, and react breaks if there are two id's (token values in this case) that are the same. 

This presents a challenge because we need uniquely identify two elements that are the same, I found one way to do this, but it present more difficulty, will try to keep this code as clean as possible.

2018-10-08 14:09 UTC, yachtcaptain23 commented
No longer needed

2018-10-08 14:09 UTC, closed without merging